account_id = "2d8e3e6f3567c9760d12a19ca2b931b3"
name = "livepeerjs"
type = "javascript"
workers_dev = false

[env.test]
workers_dev = true
kv-namespaces = [
  { binding = "KV_TEST", id = "1e47fce5bffe4994a2de6101512aaa40" }
]

[env.staging]
domain = "livepeer-staging.live"
zone_id = "4d3b36a8ea59b1ec5c9ccd76e033e485"
route = "*livepeer-staging.live/*"

[env.production]
domain = "livepeer.live"
zone_id = "d19b521e26478e5ec28f7cc905a88afa"
route = "*livepeer.live/*"